runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images
  mime_type: image/png

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /admintools\.json
  script: fantasyfootball.application
  login: admin

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: .*
  script: fantasyfootball.application


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: latest
